### ISSUE TITLE
how to get rid of unnecessary CSS code  of Kirki

### ISSUE THREAD

**Issue by oelcommits** [presscodes/kirki#2411]
Hi Ari,

please tell us how to get rid of unnecessary CSS code on our site (link in your Twitter direct)

We have <style id="kirki-inline-styles"> in code and have no idea, how to delete it. And we see this in file class-kirki-modules-css.php in folder /wp-content/plugins/ttg-core/inc/backend/kirki/modules/css  lile this public function print_styles_inline() {
		echo '<style id="kirki-inline-styles">';
		$this->print_styles();
		echo '</style>';
	}

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
