### ISSUE TITLE
How to install Kirki with Composer and PSR-4?

### ISSUE THREAD

**Issue by mehrshaddarzi** [presscodes/kirki#2414]

**Comment by contactjavas** [comment]
Hi @mehrshaddarzi :) good question! This works for me when used inside a plugin:

1. Run `composer require kirki-framework/kirki` in the project
2. Then require the autoload: `require_once 'vendor/autoload.php';`
3. After that, require the main file: `require_once 'vendor/kirki-framework/kirki/kirki.php';`
4. Kirki is ready :)

If you have `KIRKI_TEST` constant set, you'll see *Kirki Demo Panel* in your customizer :)
I created a sample plugin that uses Kirki via Composer: [kirki-composer.zip](https://github.com/kirki-framework/kirki/files/7929025/kirki-composer.zip)

I haven't tried to _use Kirki via composer inside theme_. But at least, it works when used inside a plugin.
Please let me know if this works for you too :) Just in case.. don't forget to de-activate your existing Kirki.

Thanks!

**Comment by JiveDig** [comment]
It looks like the entire `kirki-framework` package is duplicated inside itself. Is there are reason for this? 

<img width="775" alt="image" src="https://user-images.githubusercontent.com/540990/153069807-fe7b2459-aa46-4402-9b56-42e54d1dd422.png">

**Comment by JiveDig** [comment]
@MapSteps Making sure you see the above. I just confirmed in a few places that there are duplicate packages when installing via Composer. I can gitignore them but I think that should get cleaned up.

**Comment by JiveDig** [comment]
I can't even get gitignore to remove them. I think it's part of the package. Are you able to look into this one? It's double the size of the package when using it this way.

**Comment by contactjavas** [comment]
Hi @JiveDig , thanks for letting us know this issue.
Seems like the duplicated packages was because we include the sub-packages (child dependencies) under the `packages` directory.

To prevent the duplication, you'll need to prevent composer from installing those sub-packages / child dependencies. Add these lines to your composer.json:

```json
    "replace": {
        "kirki-framework/util": "*",
        "kirki-framework/l10n": "*",
        "kirki-framework/field": "*",
        "kirki-framework/url-getter": "*",
        "kirki-framework/control-base": "*",
        "kirki-framework/control-checkbox": "*",
        "kirki-framework/control-code": "*",
        "kirki-framework/control-cropped-image": "*",
        "kirki-framework/control-custom": "*",
        "kirki-framework/control-dashicons": "*",
        "kirki-framework/control-date": "*",
        "kirki-framework/control-dimension": "*",
        "kirki-framework/control-editor": "*",
        "kirki-framework/control-generic": "*",
        "kirki-framework/control-image": "*",
        "kirki-framework/control-multicheck": "*",
        "kirki-framework/control-palette": "*",
        "kirki-framework/control-radio": "*",
        "kirki-framework/control-repeater": "*",
        "kirki-framework/control-select": "*",
        "kirki-framework/control-react-select": "*",
        "kirki-framework/control-slider": "*",
        "kirki-framework/control-sortable": "*",
        "kirki-framework/control-upload": "*",
        "kirki-framework/field-dimensions": "*",
        "kirki-framework/field-fontawesome": "*",
        "kirki-framework/field-typography": "*",
        "kirki-framework/module-css": "*",
        "kirki-framework/module-editor-styles": "*",
        "kirki-framework/module-field-dependencies": "*",
        "kirki-framework/module-postmessage": "*",
        "kirki-framework/module-preset": "*",
        "kirki-framework/module-selective-refresh": "*",
        "kirki-framework/module-tooltips": "*",
        "kirki-framework/module-webfonts": "*",
        "kirki-framework/compatibility": "*",
        "kirki-framework/data-option": "*",
        "kirki-framework/module-panels": "*",
        "kirki-framework/module-sections": "*",
        "kirki-framework/module-section-icons": "*",
        "kirki-framework/control-react-colorful": "*",
        "kirki-framework/control-color": "*",
        "kirki-framework/control-color-palette": "*",
        "kirki-framework/field-background": "*",
        "kirki-framework/field-multicolor": "*"
    }
```

Here is the updated example code (I've tested it): 
[kirki-composer.zip](https://github.com/kirki-framework/kirki/files/8097809/kirki-composer.zip)

**Comment by contactjavas** [comment]
Let me know if it doesn't work for you.
For now, let me close this issue :)

**Comment by JiveDig** [comment]
That works, thanks! I couldn't get it to work with gitignore, but that helps.
