### ISSUE TITLE
Fatal error on WordPress after updating to the latest version of kirki

### ISSUE THREAD

**Issue by Sandbox-ly** [presscodes/kirki#2416]
Hello, 
After updating to the latest version of kirki I get fatal error on WordPress 

This log is from openliteserver + PHP 7.4 
(I have modified the website name and IPs for privacy)

```
#0 /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(351): Kirki\Module\CSS\Generator::css()
#1 /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(268): Kirki\Module\CSS::loop_controls()
#2 /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(179): Kirki\Module\CSS->print_styles()
#3 /home/example.com/public_html/wp-includes/class-wp-hook.php(303): Kirki\Module\CSS->print_styles_inline()
#4 /home/example.com/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#5 /home/example.com/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#6 /home/example.com/public_html/wp-includes/general-template.php(3015): do_action()
#7 in /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php on line 170
2021-12-30 13:27:57.636518 [NOTICE] [71472] [15.236.0.0:52924#example.com] [STDERR] PHP Warning:  include(fix.php): failed to open stream: No such file or directory in /home/example.com/public_html/index.php on line 8
2021-12-30 13:27:57.636548 [NOTICE] [71472] [15.236.0.0:52924#example.com] [STDERR] PHP Warning:  include(): Failed opening 'fix.php' for inclusion (include_path='.:') in /home/example.com/public_html/index.php on line 8
2021-12-30 13:27:57.937728 [NOTICE] [71472] [15.236.0.0:52924#example.com] [STDERR] PHP Fatal error:  Uncaught Error: Class '\Kirki\Field\CSS\ReactColorful' not found in /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php:170
Stack trace:
#0 /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(351): Kirki\Module\CSS\Generator::css()
#1 /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(268): Kirki\Module\CSS::loop_controls()
#2 /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(179): Kirki\Module\CSS->print_styles()
#3 /home/example.com/public_html/wp-includes/class-wp-hook.php(303): Kirki\Module\CSS->print_styles_inline()
#4 /home/example.com/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#5 /home/example.com/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#6 /home/example.com/public_html/wp-includes/general-template.php(3015): do_action()
#7 in /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php on line 170
2021-12-30 13:28:15.566373 [NOTICE] [71472] [13.38.0.0:31262#example.com] [STDERR] PHP Warning:  include(fix.php): failed to open stream: No such file or directory in /home/example.com/public_html/index.php on line 8
2021-12-30 13:28:15.566396 [NOTICE] [71472] [13.38.0.0:31262#example.com] [STDERR] PHP Warning:  include(): Failed opening 'fix.php' for inclusion (include_path='.:') in /home/example.com/public_html/index.php on line 8
2021-12-30 13:28:56.518372 [NOTICE] [71472] [13.38.0.1:51232#example.com] [STDERR] PHP Warning:  include(fix.php): failed to open stream: No such file or directory in /home/example.com/public_html/index.php on line 8
2021-12-30 13:28:56.518398 [NOTICE] [71472] [13.38.0.1:51232#example.com] [STDERR] PHP Warning:  include(): Failed opening 'fix.php' for inclusion (include_path='.:') in /home/example.com/public_html/index.php on line 8
2021-12-30 13:29:05.365879 [NOTICE] [71472] [35.180.0.0:21478#example.com] [STDERR] PHP Warning:  include(fix.php): failed to open stream: No such file or directory in /home/example.com/public_html/index.php on line 8
2021-12-30 13:29:05.365899 [NOTICE] [71472] [35.180.0.0:21478#example.com] [STDERR] PHP Warning:  include(): Failed opening 'fix.php' for inclusion (include_path='.:') in /home/example.com/public_html/index.php on line 8
2021-12-30 13:29:29.612356 [NOTICE] [71472] [13.38.0.0:28442#example.com] [STDERR] PHP Warning:  include(fix.php): failed to open stream: No such file or directory in /home/example.com/public_html/index.php on line 8
2021-12-30 13:29:29.612377 [NOTICE] [71472] [13.38.0.0:28442#example.com] [STDERR] PHP Warning:  include(): Failed opening 'fix.php' for inclusion (include_path='.:') in /home/example.com/public_html/index.php on line 8
2021-12-30 13:29:30.966302 [NOTICE] [71472] [13.38.0.0:22958#example.com] [STDERR] PHP Warning:  include(fix.php): failed to open stream: No such file or directory in /home/example.com/public_html/index.php on line 8
2021-12-30 13:29:30.966324 [NOTICE] [71472] [13.38.0.0:22958#example.com] [STDERR] PHP Warning:  include(): Failed opening 'fix.php' for inclusion (include_path='.:') in /home/example.com/public_html/index.php on line 8
2021-12-30 13:29:31.291397 [NOTICE] [71472] [13.38.0.0:22958#example.com] [STDERR] PHP Fatal error:  Uncaught Error: Class '\Kirki\Field\CSS\ReactColorful' not found in /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php:170
Stack trace:
#0 /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(351): Kirki\Module\CSS\Generator::css()
#1 /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(268): Kirki\Module\CSS::loop_controls()
#2 /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(179): Kirki\Module\CSS->print_styles()
#3 /home/example.com/public_html/wp-includes/class-wp-hook.php(303): Kirki\Module\CSS->print_styles_inline()
#4 /home/example.com/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#5 /home/example.com/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#6 /home/example.com/public_html/wp-includes/general-template.php(3015): do_action()
#7 in /home/example.com/public_html/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php on line 170

**Comment by mapsteps** [comment]
Hey there,

Is your theme available somewhere for download? I'd like to run some tests on my end with it.

Thank you.

**Comment by vdanishevskyi** [comment]
THE SAME PROBLEM :( my website don't work after last update! I use Shoptimizer Theme (Version: 2.4.5) By CommerceGurus.

**Comment by mapsteps** [comment]
Also, the error indicates something is trying to load fix.php. This is not part of our Kirki plugin, maybe that helps to further debug the issue on your end.

**Comment by mapsteps** [comment]
Alright, thank you! We're going to look into this and report back asap.

**Comment by mapsteps** [comment]
@vdanishevskyi, I see Shoptimizer is a paid theme only, can you send the theme our way so we can run some tests?

Please also notify them about the issue.

**Comment by codecreate-dev** [comment]
This was working perfectly fine until the update 1 hour ago. Shoptimizer, PHP 7.4, can you possibly rollback? Other themes are experiencing the same issue, not just Shoptimizer.

**Comment by vdanishevskyi** [comment]
@MapSteps  Ok. Check your email. I've sent you theme.

**Comment by mapsteps** [comment]
Thank you! Working on it.

**Comment by mapsteps** [comment]
We're not able to trigger the fatal error here. We have the Kirki plugin (version 4) enabled and installed + activated the Shoptimizer theme.

Can you guys think of anything we can try to trigger the error?

Thanks.

**Comment by mapsteps** [comment]
One quick thing to try: What happens if you temporarily disable all other plugins, except Kirki? Does that make any difference?

**Comment by vdanishevskyi** [comment]
all plugins disabled and website not showing on frontend (no content in below body tag)

**Comment by mapsteps** [comment]
Thanks, @vdanishevskyi for testing! Can you provide us with FTP access to your site please? Since we can't replicate this on our end, we would like to dig deeper into this on your end. connect@mapsteps.com

Thanks a ton!

**Comment by codecreate-dev** [comment]
root@hawkes:/var/www/harmandthevan/www/wp-content/plugins/kirki/packages/kirki-framework# find -name "*.php" | xargs grep  -n ReactColorful
./compatibility/src/Init.php:67:			'kirki-color'           => '\Kirki\Control\ReactColorful',
./control-color/src/Field/Color.php:23:class Color extends ReactColorful {}
./control-react-colorful/src/Control/ReactColorful.php:26:class ReactColorful extends Base {
./control-react-colorful/src/Field/ReactColorful.php:21:class ReactColorful extends Field {
./control-react-colorful/src/Field/ReactColorful.php:39:	protected $control_class = '\Kirki\Control\ReactColorful';
./control-react-colorful/src/Field/ReactColorful.php:277:		$control_classes['kirki-react-colorful'] = '\Kirki\Field\CSS\ReactColorful';
./control-react-colorful/src/Field/css/ReactColorful.php:18:class ReactColorful extends Output {
./control-repeater/src/Field/Repeater.php:149:								$subfield_value = \Kirki\Field\ReactColorful::sanitize( $subfield_value );
./field-typography/src/Field/Typography.php:558:					$value['color'] = '' === $value['color'] ? '' : \Kirki\Field\ReactColorful::sanitize( $value['color'] );
./field-multicolor/src/Field/Multicolor.php:77:			new \Kirki\Field\ReactColorful(

Is the class supposed to be  \Kirki\Field\ReactColorful or  \Kirki\Field\CSS\ReactColorful 

Is that not the issue?

**Comment by codecreate-dev** [comment]
OK so commenting out line 277 on file ./control-react-colorful/src/Field/ReactColorful.php resolves the issue but no doubt not an ideal fix

**Comment by codecreate-dev** [comment]
4.01 update fails to update

**Comment by codecreate-dev** [comment]
Updating fails when attempting to update 4.0.1 .... 

So until this is fixed, solution is :+1: 

Commenting out line 277 on file ./control-react-colorful/src/Field/ReactColorful.php resolves the issue but no doubt not an ideal fix

Update failed: The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions.
--

**Comment by mapsteps** [comment]
Okay this is a strange one. Can you please try and update the pluign manually? Simply delete the kirki folder and re-download 4.0.1 from the WordPress repository.

**Comment by codecreate-dev** [comment]
Deleted and redownloaded, it installed but exact same fatal error

**Comment by MightyDillah** [comment]
> OK so commenting out line 277 on file ./control-react-colorful/src/Field/ReactColorful.php resolves the issue but no doubt not an ideal fix

youre a life save @codecreate-dev .. i even updated kirki 4.0.1 that was just released, that did not fix the issue.

**Comment by codecreate-dev** [comment]
So 4.0.1 is still broken, so commenting out line 277 on file ./control-react-colorful/src/Field/ReactColorful.php is still the temporary fix

**Comment by pack101** [comment]
4.0.2 fixed the issue for me

**Comment by codecreate-dev** [comment]
Yeah same here 4.0.1 looks to be the same files. In fairness I guess the devs are frantically attempting to fix this and nobody can code in a rush, too much pressure.

**Comment by YellowSnoww** [comment]
we had same issue. Older version:
https://downloads.wordpress.org/plugin/kirki.3.1.9.zip

**Comment by vdanishevskyi** [comment]
4.0.2 fixed the issue for me too :) Thank you guys.

**Comment by codecreate-dev** [comment]
I can confirm 4.0.2 fixes the issue, thank you guys. Can you tell me what the problem was? I am just curious, many thanks for your work today on this

**Comment by mapsteps** [comment]
We're going to release one more update. It's been an issue with a lowercase foldername. Thanks everyone for reporting and allowing us to fix this so quickly. 

I want to apologize for the inconvenience. This is something we've overlooked.

**Comment by checkm94** [comment]
4.0.2 fixed the [issue](https://github.com/kirki-framework/kirki/issues/2417).

**Comment by YellowSnoww** [comment]
> We're going to release one more update. It's been an issue with a lowercase foldername. Thanks everyone for reporting and allowing us to fix this so quickly.
> 
> I want to apologize for the inconvenience. This is something we've overlooked.

No worries, I assume i can send the invoice? JK, keep up the good work

**Comment by codecreate-dev** [comment]
Ah was it this directory? 

./control-react-colorful/src/Field/css/ReactColorful.php

should have been?

./control-react-colorful/src/Field/CSS/ReactColorful.php

I should have spotted that myself !

**Comment by contactjavas** [comment]
Guys @codecreate-dev @YellowSnoww @Sandbox-ly , please update to `4.0.3`
In case updating through WordPress is failed, please download it manually [here](https://downloads.wordpress.org/plugin/kirki.4.0.3.zip)

**Comment by mapsteps** [comment]
yep, that was it. We never ran into this issue because we're using Windows here. I just wonder why this never came up on any of our servers or clients websites as we had included Kirki 4 for quite a while now in our own theme.

**Comment by codecreate-dev** [comment]
It only changed today, when first reported there was a new update, that was what broke it, version 4 previous to the update worked fine. I saw the notification for the update and that was at Thu Dec 30 13:41:06.403160 2021 which was the first error too because I was working on the site at the time.

**Comment by Sandbox-ly** [comment]
> yep, that was it. We never ran into this issue because we're using Windows here. I just wonder why this never came up on any of our servers or clients websites as we had included Kirki 4 for quite a while now in our own theme.

Thanks, Problem Solved :D
