### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class '\\Kirki\\Field\\CSS\\ReactColorful'

### ISSUE THREAD

**Issue by codecreate-dev** [presscodes/kirki#2418]
### Issue description:

[Thu Dec 30 13:52:45.780670 2021] [proxy_fcgi:error] [pid 67537:tid 140611532027648] [client 90.200.175.84:37516] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class '\\Kirki\\Field\\CSS\\ReactColorful' not found in /var/www/harmandthevan/www/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php:170\nStack trace:\n#0 /var/www/harmandthevan/www/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(351): Kirki\\Module\\CSS\\Generator::css()\n#1 /var/www/harmandthevan/www/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(268): Kirki\\Module\\CSS::loop_controls()\n#2 /var/www/harmandthevan/www/wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(179): Kirki\\Module\\CSS->print_styles()\n#3 /var/www/harmandthevan/www/wp-includes/class-wp-hook.php(303): Kirki\\Module\\CSS->print_styles_inline()\n#4 /var/www/harmandthevan/www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()\n#5 /var/www/harmandthevan/www/wp-includes/plugin.php(470): WP_Hook->do_action()\n#6 /var/www/harmandthevan/www/wp-includes/general-template.php(3015): do_action()...'

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

Version 4.0

### Using theme_mods or options?
Shoptimizer

### Code to reproduce the issue (config + field(s))

Failed after update, resolves when this plugin is removed but required for theme.

**Comment by mapsteps** [comment]
Duplicate https://github.com/kirki-framework/kirki/issues/2416
