### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class '\Kirki\Field\CSS\ReactColorful' not found

### ISSUE THREAD

**Issue by pack101** [presscodes/kirki#2419]
### Issue description:

Fatal error 

[30-Dec-2021 13:43:51 UTC] PHP Fatal error:  Uncaught Error: Class '\Kirki\Field\CSS\ReactColorful' not found in /wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php:170
Stack trace:
#0 /wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(351): Kirki\Module\CSS\Generator::css(Array)
#1 /wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(268): Kirki\Module\CSS::loop_controls('goya_config')
#2 /wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS.php(179): Kirki\Module\CSS->print_styles()
#3/wp-includes/class-wp-hook.php(303): Kirki\Module\CSS->print_styles_inline('')
#4 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#5 /wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Generator.php on line 170

### Version used:

4.0

### Using theme_mods or options?

Goya theme

**Comment by MapSteps** [comment]
Can you please send us a download (dropbox, google drive, etc.) download link of the theme to connect@mapsteps.com?

Thanks!

**Comment by Bjornar97** [comment]
I got the same error after updating to 4.0, and took one of our hosted websites down. Using a theme created inhouse. I downgraded to 3.1.9 and the website is up again.

**Comment by junglereef** [comment]
Hello Sirs, same issue when updated the plugin to 4.0 on theme [goya](https://goya.everthemes.com/)

**Comment by YellowSnoww** [comment]
We had same issue. Here is the older version:
https://downloads.wordpress.org/plugin/kirki.3.1.9.zip

**Comment by contactjavas** [comment]
Hi @pack101 let's focus on this #2416 thread
Since this is a duplicated issue, let me close this one in favor of that one.

**Comment by pack101** [comment]
@contactjavas 

This is concering a different theme.

**Comment by mapsteps** [comment]
@pack101, that's fine as it's basically the same issue. I think we have fixed it. Can you please update to Kirki 4.0.1?

**Comment by pack101** [comment]
@MapSteps 

No improvement yet with 4.01

I've put in a support request with the developer of the theme too with a reference to this issue.

**Comment by contactjavas** [comment]
@pack101 , @YellowSnoww @junglereef @Bjornar97 , please update to `4.0.3` that fixed the issues.
In case updating through WordPress is failed, please download it manually [here](https://downloads.wordpress.org/plugin/kirki.4.0.3.zip)

And for next progress / discussion about this issue, please go to #2416 
Thanks guys, sorry for the problems.
