### ISSUE TITLE
CSS output doesn't work in Kirki 4 (worked perfectly in Kirki 3)

### ISSUE THREAD

**Issue by surajlulla** [presscodes/kirki#2420]
I am using Kirki Customizer typography settings with 'output' to automatically assign the CSS. It worked perfectly with Kirki 3 but doesn't work anymore with Kirki 4 beta as well as today's 4.0.3 stable release:

```
Kirki::add_field($mydesignTheme, [
    'type' => 'typography',
    'settings' => 'typography_h1_settings',
    'label' => esc_html__('Advanced Typography', 'mydesign'),
    'description'    => esc_html__('Typo settings description', 'mydesign'),
    'section' => 'advanced_typography_h1',
    'default' => [
        'font-family'    => 'inherit',
        'variant'        => '700',
        'font-size'      => '',
        'line-height'    => '',
        'letter-spacing' => '0',
        'color'          => '#111111',
        'text-transform' => 'none',
        'text-align'     => 'inherit',
    ],
    'priority' => 10,
    'transport' => 'auto',
    'output' => [
        [
            'element' => 'body.single h1, body.blog h1',
        ],
    ],
]);
```

**Comment by mapsteps** [comment]
Thanks for reporting, @srjlulla. We're on it trying to replicate this on our end.

**Comment by mapsteps** [comment]
The CSS generation works fine on our end. Can you try to somehow narrow the issue down? Do you get any errors in the debug log for instance? (https://wp-pagebuilderframework.com/docs/debugging/)

**Comment by surajlulla** [comment]
There's nothing in debug log too. It worked for me in Kirki 3 but doesn't anymore in Kirki 4

**Comment by mapsteps** [comment]
Is there anything else in the theme that's extending Kirki for instance? Anything that could interefere?

One thing to try is: Remove "everything" from the theme except that particular field and check if that works. If it does, gradually bring back other options to see when things start to break.

We need to narrow this issue further down.

**Comment by surajlulla** [comment]
I understand but I think it's something minor in my Kirki integration, maybe installation or integration because everything worked perfectly with Kirki 3.
Do I need to change the inc/class-kirki-installer-section.php from Kirki 4? 

This link doesn't seem to be working https://github.com/kirki-framework/kirki/tree/master/docs/files/class-kirki-installer-section.php

**Comment by surajlulla** [comment]
It works in my Customizer Preview but doesn't work on the actual website.

**Comment by surajlulla** [comment]
I tried to debug this a bit, here's what I found.

The file packages/kirki-framework/module-css/src/CSS.php line 380, this following condition is never true in my case and $fields always returns empty

```
if (
  ( isset( $field['kirki_config'] ) && $config_id === $field['kirki_config'] ) ||
	(( 'global' === $config_id || ! $config_id ) &&
		( ! isset( $field['kirki_config'] ) || 'global' === $field['kirki_config'] || ! $field['kirki_config'] )
	)) {
		$fields[] = $field;
	}

**Comment by contactjavas** [comment]
Hi @srjlulla , could you please try this version (v4.0.4)?
[kirki.zip](https://github.com/kirki-framework/kirki/files/7796248/kirki.zip)

This is not available yet in WordPress plugins repository, so you'd need to update yours manually.
Please let us know if this fixes your issue.

Thanks!

**Comment by surajlulla** [comment]
Hi @contactjavas, I have tried v4.0.4 from your zip file but it doesn't work too :(

**Comment by contactjavas** [comment]
Hi @srjlulla , we've created another build (`v4.0.5`). Would you mind to test it against CSS output issue?
Here is the download link: [v4.0.5](https://github.com/kirki-framework/kirki/files/7801143/kirki.zip)

Thanks!

**Comment by surajlulla** [comment]
Sorry @contactjavas, v4.0.5 does not work too. I really appreciate your efforts.

**Comment by mapsteps** [comment]
Hi @srjlulla,

we have paused the 4.0 release and reverted back to 3.1.9 in the WordPress repository.

While things went smoothly for most, there were some issues we have now identified that couldn't be patched in a timely manner.

We're now looking into these issues and continue to roll out 4.0 once everything is sorted out.

**Comment by surajlulla** [comment]
Alright David. Let me know if I can help with testing or improving Kirki 4, would love to be a part of it :)

**Comment by mapsteps** [comment]
@srjlulla, can you send me a download link of your theme (Dropbox, GoogleDrive, etc.) through my contact form please? https://davidvongries.com/contact/

**Comment by surajlulla** [comment]
Yes, I have created a demo theme where I am testing and sent it to your email.

**Comment by mapsteps** [comment]
@srjlulla, can you please test this?

[kirki-4-0-8.zip](https://github.com/kirki-framework/kirki/files/7814887/kirki.zip)

**Comment by surajlulla** [comment]
Sorry, still doesn't work for me @MapSteps.
Same issue - works in the Customizer preview but no changes on the live website.

I tried Global Typography and Background color.

**Comment by mapsteps** [comment]
@srjlulla,

I think we got behind what's causing it. Can you please test this version?

[kirki-4-0-9.zip](https://github.com/kirki-framework/kirki/files/7825263/kirki-4-0-9.zip)

**Comment by surajlulla** [comment]
Oh yes @MapSteps 

The changes are working now - I tried background color, global typography and heading fonts and they finally worked! 😍
