### ISSUE TITLE
active_callback and other bugs - Kirki 4

### ISSUE THREAD

**Issue by mnmld** [presscodes/kirki#2422]
### Issue description:
Here's my initial impressions and problems i faced after upgrading to Kirki 4:

- active_callback is not working across all options in my theme. it works fine with Kirki 3

- Slider is not working properly, max number is not reaching the end of the slider.

- CSS output is not working as well for many options. website design is crashed. Still investigating what options are not doing the output properly.  (i have 100+ options unfortunately).

- Switch control background when on is visible (solid blue).

### Version used:
Kirki 4.0.3

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'crave_config', array(
	'type'        => 'slider',
	'settings'    => 'option_width',
	'label'       => esc_attr__( 'Width', 'themename' ),
	'section'     => 'layout',
	'priority'    => 11,
	'default'     => '1200',
	'choices'     => array(
						'min'  => '960',
						'max'  => '1450',
						'step' => '10'
					),
	'active_callback'  => array(
            array(
                'setting'  => 'wrapper_type',
                'operator' => '!=',
                'value'    => 'slim',
            )),
	'output' => array(
		array(
			'element'  => '.container',
			'property' => 'max-width',
			'units'    => 'px',
		),
			array(
			'element'  => '.boxed',
			'property' => 'max-width',
			'units'    => '',
			'value_pattern' => 'calc($px + 50px)',
		),
	)
	));
```

**Comment by mapsteps** [comment]
Hi @mnmld,

> active_callback is not working across all options in my theme. it works fine with Kirki 3

Can you provide me with the full code (including the control that's required in the active callback) to replicate this?

> Switch control background when on is visible (solid blue).

I'm not exactly sure what you meant by that, can you add a screenshot here?

> Slider is not working properly, max number is not reaching the end of the slider.

Testing now.

**Comment by mapsteps** [comment]
Please try to use integers, not strings in the code above. This should do the trick (just tested):

```
Kirki::add_field( 'crave_config', array(
	'type'     => 'slider',
	'settings' => 'option_width',
	'label'    => esc_attr__( 'Width', 'themename' ),
	'section'  => 'layout',
	'priority' => 11,
	'default'  => 1200,
	'choices'  => array(
		'min'  => 960,
		'max'  => 1450,
		'step' => 10,
	),
	'output'   => array(
		array(
			'element'  => '.container',
			'property' => 'max-width',
			'units'    => 'px',
		),
		array(
			'element'       => '.boxed',
			'property'      => 'max-width',
			'units'         => '',
			'value_pattern' => 'calc($px + 50px)',
		),
	),
) );
```

**Comment by mapsteps** [comment]
Just letting you know that with the next update, the min/max/step values can be passed as strings and don't necessarily need to be integers any more. We've fixed that.

**Comment by mnmld** [comment]
Thanks @MapSteps for the support.

**Here's a code that for two simple options which have active_callback not working in addition to CSS output is not working as well for the second option.**

```
Kirki::add_field( 'mnmld_config', array(
	'type'        => 'radio',
	'settings'    => 'mnmld_logo_type',
	'label'       => esc_html__( 'Site Logo Type', 'mnmld' ),
	'section'     => 'title_tagline',
	'default'     => 'image',
	'priority'    => 21,
	 
	'choices'     => array(
		'text' => esc_attr__( 'Text', 'mnmld' ),
		'image' => esc_attr__( 'Image', 'mnmld' ),
	),
) );

Kirki::add_field( 'mnmld_config', array(
	'type'        => 'typography',
	'settings'    => 'mnmld_logo_text_styling',
	'label'       => esc_attr__( 'Text Logo Styling', 'mnmld' ),
	'section'     => 'title_tagline',
	'default'     => array(
		'font-family'    => 'Noto Serif',
		'variant'        => 'regular',
		'font-size'      => '2rem',
		'letter-spacing' => '0',
		'color'          => '#111',
		'text-transform' => 'none',
	),
	'priority'    => 24,
	'choices' => [
	'fonts' => [
		'standard' => ['serif', 'sans-serif', 'monospace'],
		],
	],
	'active_callback'  => array(
            array(
                'setting'  => 'mnmld_logo_type',
                'operator' => '==',
                'value'    => 'text',
            ),
        ),
	'output'      => array(
		array(
			'element' => '.logo .logo-text a',
		),
	),
) );
```

**Comment by mnmld** [comment]
For the CSS output problem, i tried the unofficial version 4.0.4 mentioned [here ](https://github.com/kirki-framework/kirki/issues/2425#issuecomment-1003371909)and it seems to be working properly again.

**Comment by contactjavas** [comment]
Hi @mnmld , in case you would like to test our newest build (which is not available yet in WP plugins repo), here is the download link: [v4.0.5](https://github.com/kirki-framework/kirki/files/7801143/kirki.zip)

**Comment by mapsteps** [comment]
Hey @mnmld, I just tested your code above regarding the `active_callback` issue. It works fine for me (screenshot below).

- Do you get any errors in the browser console?
- In case you're extending Kirki in any way, can you remove those codes to check if it makes any difference?
- Please try to keep removing things from your theme to check if it suddenly starts working at some point. This would allow you to narrow down what's causing the issue

![grafik](https://user-images.githubusercontent.com/22119831/147934644-789c0b6c-8586-4f8a-9d27-7026ed4542e1.png)

I can confirm that the CSS output doesn't work for me either on that particular typography field. We'll keep you posted.

**Comment by mnmld** [comment]
Thanks @contactjavas & @MapSteps,

For the `active_callback` issue, i managed to fix the problem. it was a problem with two-dimensional array for active_callback (which was working fine in kirki 3), but anyway it's fixed now.

For the CSS output, still facing some difficulties in cases similar to the example below:

```
<?php
Kirki::add_field('config', array(
    'type' => 'radio-buttonset',
    'settings' => 'clr',
    'label' => esc_html__('Color', 'lang') ,
    'section' => 'type',
    'default' => 'preset',
    'priority' => 10,
    'choices' => array(
        'preset' => esc_attr__('Presets', 'lang') ,
        'custom' => esc_attr__('Custom', 'lang') ,
    ) ,
));
?>
```

The example is an option to choose between color presets or pick custom one. 
For the two sub options (`preset` and `custom`) I use that same output `'output' => $color_array,`.
The problem is that kirki 4 tends to use the value of the last option always (in this case `custom`) even if the selected option is `presets`.

Let me know if you want to send the full code for similar issue to replicate it.

**Comment by contactjavas** [comment]
Hi @mnmld , awesome!
We're also just fixed this issue (the `active_callback`).
Here is the link for the new build: [v4.0.6](https://github.com/kirki-framework/kirki/files/7803040/kirki.zip)
However, thank you for fixing it!

And yes, we're also still having the problem with the CSS output.
Will let you know once we have fixed the CSS issue.

**Comment by mapsteps** [comment]
@mnmld, 

> it was a problem with two-dimensional array for active_callback (which was working fine in kirki 3), but anyway it's fixed now.

Can you share the fix & code-example to recreate this with us please?

The CSS generation issue is on our list already. We're looking into this asap.

**Comment by MapSteps** [comment]
Using your code above for the radio buttonset, this seems to work fine on my end.

![grafik](https://user-images.githubusercontent.com/22119831/147961115-71eddce3-ab5b-4ab3-910d-88100067d2c9.png)
Presets is the default for me.

**Comment by mnmld** [comment]
Sure. Provided that 4.0.6 fixed the problem, i will share the original case (which works again with no fix from my end after 4.0.6).

```
$visibility = array(
			array(
				'setting'  => 'page_layout',
				'operator' => 'in',
				'value'    => 'section1'
			),
		);
```
this is an `active_callback` value that is repeated for many options in a specific section.
`'active_callback' => $visibility,`

The fix was removing the nested arrays from `$visibility`
```
$visibility = array(
				'setting'  => 'page_layout',
				'operator' => 'in',
				'value'    => 'section1'
		);
```
and adding it again in the value
`'active_callback' => array($visibility),`

**Comment by mapsteps** [comment]
Awesome, thank you! :)

**Comment by mnmld** [comment]
> Using your code above for the radio buttonset, this seems to work fine on my end.
> 
> ![grafik](https://user-images.githubusercontent.com/22119831/147961115-71eddce3-ab5b-4ab3-910d-88100067d2c9.png) Presets is the default for me.

The problem is with the CSS output for the sub options not this option itself (radio buttonset are good). Would you please provide an email maybe to send you the code privately.

**Comment by mapsteps** [comment]
Yea, that's why I deleted my reply 😆
I first thought it was on the customizer side but then realized it's about the CSS generation which is already on our list.

**Comment by mnmld** [comment]
No worries, You efforts are much appreciated!

**Comment by mapsteps** [comment]
Hey @mnmld, I said earlier that I was able to confirm the CSS ouptut bug - turned out I made a mistake there and the CSS output does actually work fine on my end. Can you send me a copy of your theme (download link, Dropbox, Google Drive, etc) through my contact form? https://davidvongries.com/contact/

**Comment by mnmld** [comment]
I've just send it through contact form.
