### ISSUE TITLE
Default value returns 'null' after 4.0.3 update

### ISSUE THREAD

**Issue by Gnodesign** [presscodes/kirki#2423]
As mentioned on this ticket https://github.com/kirki-framework/kirki/issues/2421 after update 4.0.3 all of my themes have issues picking up the default values of the added fields which results in php errors in the frontend. This could be fixed with certain checks to avoid the errors but the default value still will not pass, unless the user changes the field's value via the customizer and clicks on "publish".

After some digging to see what the issue could be I tried to **var_dump** the field in the frontend and I found out that the field's default value is only shown when the customizer is opened, in the frontend (without the customizer) the value is 'null'.

### Version used:
Latest version: 4.0.3

### Using theme_mods or options?
theme_mods

**Comment by mapsteps** [comment]
Hey @Gnodesign,

thanks for opening a new issue.

I just want to make sure we're on the same page. If a value is set in the customizer (passed as a default in Kirki) it has not been saved to the database.

Generally speaking, to get the default value, you would do something like this:

`
get_theme_mod( 'your_example_color_setting', '#ffffff'  );` (where #ffffff acts as the default).

If the value is then changed by the user, it will use that value instead of the given default.

Reference - https://developer.wordpress.org/reference/functions/get_theme_mod/

**Comment by Gnodesign** [comment]
I have been using on all my themes since Kirki's early versions this method `Kirki::get_option( $config_id, $field_id );` and it used to work fine on 3.1.9. Has this been changed?

**Comment by mapsteps** [comment]
Ohh, I thought you were using theme mods as per the issue description above. Can you share an example code how you register a control on your end + the config? Also, how you would then get the respective setting/value on the frontend?

We're going to try & recreate this on our end.

**Comment by Gnodesign** [comment]
Sending a quick simple representation of how everything works. When I rollback to the previous version it works just fine. One of my themes uses Kirki for the past 3 years in this workflow. 

Config:
```
Kirki::add_config( 'themename',
  [
	  'capability'  => 'edit_theme_options',
	  'option_type' => 'theme_mod',
  ]
);
```

The fields:
```
Kirki::add_field( 'themename', [
    'type'        => 'switch',
    'settings'    => 'header_cta',
    'label'       => esc_html__( 'Header CTA', 'themename' ),
    'description' => esc_html__( 'Turn the switch "OFF" to disable Header CTA.', 'themename' ),
    'section'     => 'header',
    'default'     => true,
    'priority'    => 10,
] );
```

Output the value:
```
Kirki::get_option( 'themename', 'header_cta' );
```

**Comment by Gnodesign** [comment]
Also as mentioned previously, if you **var_dump** the output the default value will only show when the customizer is opened, without the customizer the result will always be 'null', it doesn't matter what type the field is.

**Comment by ravishakya** [comment]
Same thing is happening to me also. The default value is not working on 'dimensions' field.

Here is my code

````
Kirki::add_field( 'bizberg', [
	'type'        => 'dimensions',
	'settings'    => 'banner_spacing',
	'label'       => esc_html__( 'Spacing', 'bizberg' ),
	'section'     => 'front_page_hero',
	'default'     => apply_filters( 'bizberg_banner_spacing', [
		'padding-top'    => '65px',
		'padding-bottom' => '65px',
		'padding-left'   => '0px',
		'padding-right'  => '0px',
	]),
	'choices'     => [
		'labels' => [
			'padding-top'  => esc_html__( 'Top', 'bizberg' ),
			'padding-bottom'  => esc_html__( 'Bottom', 'bizberg' ),
			'padding-left' => esc_html__( 'Left', 'bizberg' ),
			'padding-right' => esc_html__( 'Right', 'bizberg' ),
		],
	],
	'active_callback'    => array(
		array(
			'setting'  => 'slider_banner',
			'operator' => '==',
			'value'    => 'banner',
		),
	),
	'transport' => 'postMessage',
	'js_vars'   => [
		[
			'element'  => '.breadcrumb-wrapper .section-title',
			'function' => 'css'
		]
	]
] );
````

I am using the code suggested by the aristath. https://github.com/kirki-framework/kirki/issues/1712#issuecomment-352031449

````
function my_theme_get_theme_mod( $theme_mod ) {
	$default_value = '';
	if ( class_exists( 'Kirki' ) && isset( Kirki::$fields[ $field_id ] ) && isset( Kirki::$fields[ $field_id ]['default'] ) ) {
		$default_value = Kirki::$fields[ $field_id ]['default'];
	}
	$value = get_theme_mod( $field_id, $default_value );
}
````

$banner_spacing = my_theme_get_theme_mod( 'banner_spacing' );

**Comment by contactjavas** [comment]
Hi @Gnodesign , we're working on this.
Will let you know the update here.

Thanks for providing the codes & example.

**Comment by mapsteps** [comment]
@Gnodesign, can you send me a download link of your theme via email please?

**Comment by contactjavas** [comment]
Hi @Gnodesign , could you please try this version (v4.0.4)?
[kirki.zip](https://github.com/kirki-framework/kirki/files/7796248/kirki.zip)

This is not available yet in WordPress plugins repository, so you'd need to update yours manually.
We have tested this in our side, and it fixes the `Kirki::get_option` usage.
Please let us know if this fixes your issue.

Thanks!

**Comment by Gnodesign** [comment]
@MapSteps I just sent you one of my themes to your email.

@contactjavas will test right now and keep you updated.

**Comment by mapsteps** [comment]
@Gnodesign, haven't received it yet. Did you send me a zip (which might get blocked) or a download link?

**Comment by Gnodesign** [comment]
I just received email that it didn't get delivered. Will send it via wetransfer right now.

**Comment by Gnodesign** [comment]
@MapSteps Everything related to Kirki can be found in `/inc/customizer.php`. The output function is `cocoon_get_option()`.

**Comment by mapsteps** [comment]
Awesome, thank you! Just received the download link :)

**Comment by mapsteps** [comment]
While I can't get the preloader to disappear, the default values now seem to render properly, @Gnodesign.

**Comment by Gnodesign** [comment]
@MapSteps I am testing 4.0.4 and it seems everything renders well now. The only issue I am facing is the rendering of the CSS output. For example, if you check `/inc/customizer.php` line 533, the selected typography won't output to the body element, this happens with any output.

Can you please check this as well, I believe this is also a bug.

**Comment by Gnodesign** [comment]
The issue mentioned here https://github.com/kirki-framework/kirki/issues/2425 seems to continue even with 4.0.4.

**Comment by mapsteps** [comment]
Just in general, I want to mention that callking `Kirki::get_option()` has been deprecated a long time ago and should no longer be used. It's from the very first version of Kirki actually.

There is backwards-compatibility in place which is now partially fixed. We continue to look into this.

**Comment by Gnodesign** [comment]
I see, I didn't know that to be honest, thank you for letting me know. So the best way to handle this is by switching to `get_theme_mod()`?

I have 6 themes using this method that would take quite some time to convert everything to this method. Do you know any workaround so that I can add this to `cocoon_get_option()` function? This way I can just adjust the function instead of replacing everything in the theme.

**Comment by mapsteps** [comment]
I would try to update 1 theme to check if that also fixes the CSS generation (there is a chance it does). If that works, switching to `get_them_mod()` is the best option.

**Comment by Gnodesign** [comment]
I don't think the CSS generation has anything to do with it since it's being handled by Kirki and not called anywhere. As far as it goes for `Kirki::get_option()` seems to be working fine with 4.0.4.

**Comment by Gnodesign** [comment]
The css generation issue has also been mentioned here https://github.com/kirki-framework/kirki/issues/2422, https://github.com/kirki-framework/kirki/issues/2420. Any news on this?

**Comment by contactjavas** [comment]
Hi @Gnodesign , we've created another build (`v4.0.5`). Would you mind to test it against CSS output issue?
Here is the download link: [v4.0.5](https://github.com/kirki-framework/kirki/files/7801143/kirki.zip)

Thanks!

**Comment by Gnodesign** [comment]
@contactjavas Still the same, everything that is related to the custom css output in all of my themes still doesn't work.

**Comment by mapsteps** [comment]
Thanks for testing, @Gnodesign. We have paused the Kirki 4 release in the WordPress repository as we were not able to fix the reported bugs in a timely manner. We continue to look into this and update you asap.

**Comment by mapsteps** [comment]
Hey @Gnodesign,

we digged a bit deeper into Cocoon and might have figured out what's causing this. Please see the code below.

File: `wp-content/themes/cocoon/inc/customizer.php`

```
// This is default by Cocoon.
if ( class_exists( 'Kirki' ) ) {
	add_action( 'init', 'cocoon_customize_init', 30 );
} else {
	$cocoon_customize = new Cocoon_Customize( cocoon_customize_settings() );
}

/**
 * This is how it should be.
 * This will create warnings if Kirki is not installed, which needs to be handled by the theme developer.
 */
if ( class_exists( 'Kirki' ) ) {
	$cocoon_customize = new Cocoon_Customize( cocoon_customize_settings() ); // Call it directly!
}
```

**Comment by mapsteps** [comment]
Well, instead of calling it directly - you can set the priority of `add_action( 'init', 'cocoon_customize_init', 30 );` to 5, not 30. That does it as well :) Everything under the default prioriy (10) seems to work.

**Comment by Gnodesign** [comment]
@MapSteps As you mentioned, I lowered the priority and everything seems to work fine now with 4.0.5. Never thought about it since it was working for the past years. Thank you so much for letting me know. 

I also played around with 4.0.5 and everything was working fine except the css issue that is now also fixed. :)

**Comment by mapsteps** [comment]
Beautiful! :) We're making sure all other remaining issues are resolved before re-releasing version 4. Thank you so much for troubleshooting & testing!

**Comment by mapsteps** [comment]
Hey @Gnodesign,

would you mind test the latest dev-build once again? You should be able to bring back the priority to 30. Just want to make sure everytyhing is still working correctly with the latest version.

Thank you!

[kirki-4-0-9.zip](https://github.com/kirki-framework/kirki/files/7825254/kirki-4-0-9.zip)

**Comment by Gnodesign** [comment]
Hey @MapSteps,

Just tested it with the version you sent me on 3 of my themes and it seems to work fine now when the priority is 10 or higher. :)
