### ISSUE TITLE
Kirki 4 generates a lot of nodes

### ISSUE THREAD

**Issue by haikbvn** [presscodes/kirki#2427]
### Issue description:
I'm using Kirki 4 and it generates a lot of nodes?

<img width="1552" alt="Screen Shot 2022-01-01 at 19 49 53" src="https://user-images.githubusercontent.com/1848623/147851343-25fd44f5-d8f2-4caa-93b0-af311ac4254e.png">

### Version used: v4.0.3
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Using theme_mods or options?
Using theme_mods

**Comment by mapsteps** [comment]
Hi @haikbvn,

Kirki 4 is built differently from the ground up and each control now registers their own style & script.
