### ISSUE TITLE
Bugs with the latest version

### ISSUE THREAD

**Issue by Guillaume5464** [presscodes/kirki#2428]
### Issue description:
The changes I do with the color of the page's title don't make them and also the same issue with the background image at the title of the pages and I can't change the width of the pages.

### Version used:
I'm using teh 4.0.3 version of kirki and using the them BuddyX, version 4.2.8

**Comment by contactjavas** [comment]
Hi @Guillaume5464  , we've created another build (`v4.0.5`). Would you mind to test it against CSS output issue?
Here is the download link: [v4.0.5](https://github.com/kirki-framework/kirki/files/7801143/kirki.zip)

Thanks!

**Comment by Guillaume5464** [comment]
Hi, thank you for the new version but the issues are still there, when I want to personnalize the title of the page, change the color or the background, at the under header tab, for the background i can see it but when i go the website, it's not there anymore... and for the color of the title, the colors dont change at all. And for the width, when I go the general tab, I can see the changes but not on the website. :-(

**Comment by Guillaume5464** [comment]
Hey, so I downgrading to the version 3.1.9, the one that the theme BuddyX 4.2.8 propose to me and it's working, I don't know what's going with the version 4. I will see with the others 4 if its working or not.
Thank you

**Comment by mapsteps** [comment]
@Guillaume5464, can you send us a copy of the BuddyX theme please? You can send us a Dropbox or Google Drive link, etc. through my contact form - https://davidvongries.com/contact/

Thank you!

**Comment by mapsteps** [comment]
@Guillaume5464, can you please test the latest dev-build?

[kirki-4-0-8.zip](https://github.com/kirki-framework/kirki/files/7814902/kirki.zip)

**Comment by Guillaume5464** [comment]
Hi @MapSteps with the version 4.0.8 it's still not working :-( and what part of the copy of the BuddyX theme do you want me to send you?

**Comment by contactjavas** [comment]
Hi @Guillaume5464 , are you using free BuddyX version or the PRO one?

If you're using the PRO version, then we don't have access to that theme.
For faster test & troubleshoot in our side, then the whole BuddyX theme folder is necessary.

**Comment by mapsteps** [comment]
@Guillaume5464, can you please test version 4.0.9 below to check if that makes any difference?
[kirki-4-0-9.zip](https://github.com/kirki-framework/kirki/files/7825268/kirki-4-0-9.zip)

**Comment by contactjavas** [comment]
Update: [v4.0.11](https://github.com/kirki-framework/kirki/files/7840678/kirki.zip)

**Comment by Guillaume5464** [comment]
Hi guys, nope it's still not working with version 4.0.9 and 4.0.11.

**Comment by contactjavas** [comment]
Hi @Guillaume5464 , using the BuddyX free version, we're able to reproduce the issue.
We've fixed this issue in `v4.0.13`. I've tested it.
Download link: [v4.0.13](https://github.com/kirki-framework/kirki/files/7848643/kirki.zip)

Please let us know if this version fixes the issue on your side.
Thanks!

**Comment by Guillaume5464** [comment]
Hi @contactjavas yeeeeeessss its working, I have the BuddyX free version too. 
Thanks a lot for your work.
Have a good Day! :-)
