### ISSUE TITLE
Options are not saved in 4.0.x updates

### ISSUE THREAD

**Issue by purethemes** [presscodes/kirki#2429]
### Issue description:
Changes in customizer are not saved. https://cln.sh/9jBm8i

### Version used:
I tested it on 4.0.3, 4.0.4 and now on 4.0.5, downgrading to 3.1.9 fixes the problem

### Using theme_mods or options?
I'm using Options. I had it configured in the theme with the Kirki fallback wrapper class  (the one that used to  be here https://github.com/aristath/kirki/tree/master/docs/files/class-my-theme-kirki.php but it's gone ) but even without it where it directly is added in code it doesn't work 

### Code to reproduce the issue (config + field(s))
```

Kirki::add_config( 'listeo', array(
    'option_type' => 'option',
    'capability'  => 'edit_theme_options',
) );
    
    
Kirki::add_panel( 'homes_panel', array(
    'priority'    => 21,
    'title'       => __( 'Home Search Options', 'listeo' ),
    'description' => __( 'Options for Home Page templates', 'listeo' ),
) );



Kirki::add_section( 'homepage', array(
    'title'          => esc_html__( 'General Home Search Template Options', 'listeo'  ),
    'description'    => esc_html__( 'Options for Page with Search form', 'listeo'  ),
    'priority'       => 11,
    'capability'     => 'edit_theme_options',
    'panel'     => 'homes_panel',
    'theme_supports' => '', // Rarely needed.
) );

Kirki::add_field( 'listeo', array(
		    'type'        => 'text',
		    'settings'     => 'listeo_home_title',
		    'label'       => esc_html__( 'Search Banner Title', 'listeo' ),
		    'description' => esc_html__( 'Title above search form ', 'listeo' ),
		    'section'     => 'homepage',
		    'default'     => esc_html__('Find Nearby Attractions','listeo') ,
		    'priority'    => 1,
		) );
```

**Comment by mapsteps** [comment]
Hi @purethemes,

Just real quick - how are you calling `listeo_home_title` on the frontend and what did the wrapper function you've mentioned look like?

Thank you.

**Comment by mapsteps** [comment]
Hi @purethemes,

this should now be fixed in version 4.0.7. Thank you for reporting this. You can download & test version 4.0.7 here - [kirki-4.0.7.zip](https://github.com/kirki-framework/kirki/files/7803408/kirki.zip)

**Comment by purethemes** [comment]
Hi

I can confirm that 4.0.7 fixes that problem, thank you very much, I know how hard such situations are with that 4.0.x updates. Thank you for your work. When do you expect to push 4.0.7 to wordpress.org?

**Comment by mapsteps** [comment]
@purethemes, we still have a few things on our list before we continue to roll out Kirki 4. There is no estimate currently. We hope to get everything sorted by the end of the week.
