### ISSUE TITLE
wp.customize.preview.send no longer works

### ISSUE THREAD

**Issue by ludjon** [presscodes/kirki#2431]
Hi, on codeless-page-builder wp.customize.preview.send no longer works when activating the kirki 4.0.3

Are you able to identify the issue?

Thanks

**Comment by mapsteps** [comment]
@ludjon, thanks for letting us know! We're going to look into this.

**Comment by contactjavas** [comment]
Hi @ludjon , do you mean this plugin: https://wordpress.org/plugins/codeless-page-builder/ ? How can we recreate this issue on our end?

**Comment by ludjon** [comment]
Yes

**Comment by mapsteps** [comment]
@ludjon, how can we recreate the issue? We can't seem to get the plugin to activate. Also, what theme are you using?

**Comment by ludjon** [comment]
I just want from you to know about the wp.customize.preview.send function that is no longer working. I see that you used that on postmeta module but you removed it on 4.0 version.

**Comment by ludjon** [comment]
I am trying to send some data from customize-preview to customize-controls using wp.customize.preview.send

**Comment by ludjon** [comment]
@MapSteps I think i found the issue, what is the equivalent of 'kirki-script' handler on the new version? I use it on wp_enqueue_script dependencies.

Thanks

**Comment by mapsteps** [comment]
@ludjon, kirki-script no longer exists. All controls now load their own respective script & style.

**Comment by ludjon** [comment]
But is one control that loads all the time?

**Comment by mapsteps** [comment]
One possible solution would be - instead of having a dependency - to load it regardless, just maybe with a priority of 999 to ensure it loads last?

**Comment by ludjon** [comment]
I tried with kirki-control-base and it worked
