### ISSUE TITLE
Icons for Panels & Sections

### ISSUE THREAD

**Issue by mnmld** [presscodes/kirki#2432]
### Issue description:
Icons for panels and sections are no longer displaying in Kirki 4
![image](https://user-images.githubusercontent.com/79640203/148286561-fb735f99-f0d0-4881-9bb4-5c9887f35e69.png)
screenshot from kirki 3.1.9

### Version used:
4.0.8

### Using theme_mods or options?
theme_mods

**Comment by contactjavas** [comment]
Hi @mnmld , thanks for reporting this.
Would you mind to also paste your related code here?

Thank you

**Comment by mnmld** [comment]
Sure.
```
<?php
Kirki::add_section('misc', array(
    'title' => esc_html__('Misc', 'example') ,
    'priority' => 10,
    'capability' => 'edit_theme_options',
    'icon' => 'dashicons-clipboard'
));
?>
```

**Comment by artkrsk** [comment]
The issue still appears to be relevant in 4.0.9:

### New Kirki 4.0.9:
![2022-01-10_10-55-35](https://user-images.githubusercontent.com/15735987/148733707-326c899b-b5ad-4c16-800b-431d76c90b02.png)

### Old Kirki 3.1.9:
![2022-01-10_10-56-31](https://user-images.githubusercontent.com/15735987/148733774-9f0ae26c-8c34-4036-8a83-6416ce9695ac.png)

**Comment by contactjavas** [comment]
Hi @artkrsk , which version 3 do you use? I tested on `v3.19` and the section icon is not there.

**Comment by contactjavas** [comment]
Hi @artkrsk ! Yea, the section icons module was missing.
Please try this `v4.0.11`. Download link: [v4.0.11](https://github.com/kirki-framework/kirki/files/7840678/kirki.zip)
I've tested it, and it brings back the icons feature.

Thanks!

**Comment by artkrsk** [comment]
@contactjavas Icons appear fine now. Thanks.

**Comment by mnmld** [comment]
Many thanks @contactjavas!
