### ISSUE TITLE
Field definition is empty in \Kirki::$fields

### ISSUE THREAD

**Issue by sebastianthulin** [presscodes/kirki#2436]
### Issue description:
Previously we were able to fetch the full field definition by referencing $fields = \Kirki::$fields;. This has stopped working in version 4 and above. This is handy to have available for various tasks. We are using it to automatically provide fields to out controllers. 

I understand that this may not be an indended use-case, but we would be happy if it can be reimplemented. Happy to help with this, if some pointers are given in the direction of "the correct way of implementation". 

### Version used:
4.0.9

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
add_action('wp', function() { var_dump(\Kirki::$fields); }); 

Any config will return an empty array. 

### Example implementation: 
https://github.com/helsingborg-stad/Municipio/blob/3.0/develop/library/Customizer/Applicators/Modifiers.php#L21

Description: A simple implementation of this functionality, to add modifiers tor components by pure kirki configuration & a filter. Without the need of writing more code.

**Comment by sebastianthulin** [comment]
Looks like the fields are added here to index: https://github.com/kirki-framework/kirki/blob/master/packages/kirki-framework/compatibility/src/Field.php#L343 . This class is however never initialized on my install.

**Comment by contactjavas** [comment]
Hi @sebastianthulin , thanks for posting the issue :)
Can you try to use `Kirki::$all_fields` instead? Would that work for your use-case?

Thanks

**Comment by sebastianthulin** [comment]
Thanks! It seems like it, there are a minor difference regarding the data structure of output. Previously output was embedded in the $args sub element. 

3.0 / $fields
$field['args']['output']

4.0 / $all_fields
$field['output']

This change will however not be an issue for me.
