### ISSUE TITLE
[DevTools] Failed to load control-checkbox source map

### ISSUE THREAD

**Issue by haikbvn** [presscodes/kirki#2437]
### Issue description:
Hi,
```
DevTools failed to load source map: Could not load content for https://wpdev.local/wp-content/plugins/kirki/packages/kirki-framework/control-checkbox/dist/control.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://wpdev.local/wp-content/plugins/kirki/packages/kirki-framework/control-checkbox/dist/control.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

### Version used: 4.0.3
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

**Comment by contactjavas** [comment]
Hi @haikbvn , please update to `v4.0.11`. It includes the source maps for control-checkbox.
Download link: [v4.0.11](https://github.com/kirki-framework/kirki/files/7840678/kirki.zip)

Thanks :)
