### ISSUE TITLE
Override text-domain

### ISSUE THREAD

**Issue by liveweb22** [presscodes/kirki#2438]
### Issue description:
Override text-domain 

### Version used:
3.1.9

### Code to reproduce the issue (config + field(s))

Hi! I am currently developing a theme for wordpress and using kirki. I checked the theme and there is a kirki domain that is not supported. I also found L10n on github and I don't know exactly how to include it in the theme. Can you guide me? Thanks in advance.  This is main init for kirki - 

require_once WP_THEME_DIR . '/assets/kirki/kirki.php';

**Comment by contactjavas** [comment]
Hi @liveweb22 , could you please elaborate more on the issue? Like your use-case and how currently you handle the l10an?
Do you use plugin such as Loco translate?

Thanks!

**Comment by liveweb22** [comment]
Hi, no. For WordPress Customizer i use Kirki Framework and also i included this in my theme. I want to ovveride text-domain kirki with my text-domain, because theme checker says. It has nothing to do with loco translate, I would like to change the domain to my domain and I saw that this module does this, but I don't see any documentation how I could implement it.

// Kirki.
require_once WP_THEME_DIR . '/assets/krampus-theme/kirki.php';

This is path for kirki that requires on my theme. Kirki text-domain must be rename to my own tex-domain.

Theme Check
--------------


WARNING: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs. The domains found are kirki, kc-theme

**Comment by mapsteps** [comment]
@liveweb22, please check my reply here - https://github.com/kirki-framework/kirki/issues/142

**Comment by liveweb22** [comment]
I understand now. Thank you for your help :).
