### ISSUE TITLE
Special Characters not showing on control label

### ISSUE THREAD

**Issue by ravishakya** [presscodes/kirki#2440]
after version 4

![image](https://user-images.githubusercontent.com/11089018/149609000-c5f28585-9e18-44db-8aaa-00097aaf10b8.png)

before version 4

![image](https://user-images.githubusercontent.com/11089018/149609087-fcd9454f-2a96-413d-ad58-b7adc3f0b88c.png)

**Comment by contactjavas** [comment]
Hi @ravishakya , thanks for letting us know this issue :)
Please try this `v4.0.15` update: [v4.0.15](https://github.com/kirki-framework/kirki/files/7887218/kirki.zip)

Thanks :)

**Comment by ravishakya** [comment]
Now its working.

Thank You
