### ISSUE TITLE
Don't work "editor,dashicons" Contrals in repeater

### ISSUE THREAD

**Issue by mushabberul** [presscodes/kirki#2441]
### Issue description:
When I use an editor or dashicons controls as a field inside a repeater control, it doesn't show on the customizer.
Text control inside the same repeater shows correctly

### Version used: Latest version
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Using theme_mods or options?
I am using theme_mod()

### Code to reproduce the issue (config + field(s))

```php
Kirki::add_field( PRESENTO_CUSTOMIZER_CONFIG_ID, [
	'type'        => 'repeater',
	'label'       => esc_html__( 'Enter Your Client Logos', 'presento' ),
	'section'     => 'client_logos',
	'priority'    => 10,
	'row_label' => [
		'type'  => 'text',
		'value' => esc_html__( 'Enter Logo', 'presento' ),
	],
	'button_label' => esc_html__('Add New', 'presento' ),
	'settings'     => 'client_logos_display',
	'fields' => [
		'client_logo_link' => [
			'type'        => 'editor',
			'label'       => esc_html__( 'Logo', 'presento' ),
		],
	]
] );
```

**Comment by mapsteps** [comment]
Hi @sabbirmia002,

Only a limited amount of controls are currently supported inside the repeater field. Editor & dashicon fields are not supported.

Currently supported:
- Image
- Text
- URL
- Select
- Upload
- Dropdown Pages
- Color
- Checkbox
- Radio
- Radio-image
- Textarea
