### ISSUE TITLE
Switch control with default set to OFF shows as ON

### ISSUE THREAD

**Issue by AlxMedia** [presscodes/kirki#2444]
### Issue description:
All of my 40 themes have this issue when updating. Switch controls set to OFF as default shows as ON and are broken.

### Version used:
Kirki 4.0.15

### Code to reproduce the issue (config + field(s))
Example field:
```
// Blog: Frontpage Widgets Bottom
Kirki::add_field( 'incolor_theme', array(
	'type'			=> 'switch',
	'settings'		=> 'frontpage-widgets-bottom',
	'label'			=> esc_html__( 'Frontpage Widgets Bottom', 'incolor' ),
	'description'	=> esc_html__( '2 columns of widgets', 'incolor' ),
	'section'		=> 'blog',
	'default'		=> 'off',
) );
```
Or download one of my themes here and check: https://alx.media/themes/incolor/ (/functions/kirki/ folder needs to be updated to 4.0.15)
Customize > Theme Options > Blog > Frontpage Widgets Top/Bottom (shown as ON with it set to OFF)

(The code could look like this in a theme:)
```
<?php if ( get_theme_mod('my-option','off') == 'on' ) : ?>
```

**Comment by AlxMedia** [comment]
I'd do anything for backwards compatibility here on the switch. Rebuilding many options in each theme, and then do it 40 times is... well, far from fun.

**Comment by mapsteps** [comment]
We got you, this was an oversight. I'll report back once this is fixed! :)

**Comment by contactjavas** [comment]
Hi @AlxMedia , thanks a lot for reporting this issue.
It's now fixed (I have tested it) in `v4.0.16`. Download link: [v4.0.16](https://github.com/kirki-framework/kirki/files/7927233/kirki.zip)
Please let us know if this version fixes your issue :)

Thanks!

**Comment by AlxMedia** [comment]
Seem to work great from the testing I've done, thanks for this @contactjavas - I can now sleep without worrying about having to remake 40 themes :D

**Comment by contactjavas** [comment]
Hi @AlxMedia , I'm sorry, `v4.0.16` contains some notice messages if you don't define the `default` argument.
Please update to `v4.0.17` that include the fix for that. Download link: [v4.0.17](https://github.com/kirki-framework/kirki/files/7928385/kirki.zip)

Thanks :)
