### ISSUE TITLE
No CSS output if default is empty

### ISSUE THREAD

**Issue by idlevibes95** [presscodes/kirki#2446]
### Issue description:
I have a color control where the `default` is empty (I need it to stay empty). While no CSS is output when Kirki is installed, when I deactivate it, the CSS is output, but like this:

border-bottom: 1px solid ;

And there's a black border instead of no border. I have a few controls like this and I need them to stay empty, but the theme looks messed up when it's first uploaded to a blog (if Kirki is not installed). I've used the class-my-theme-kirki file, too, so I'm wondering if that's what's causing the problem.

Is there a way to stop CSS from being output if `default` is empty?

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
3.1.9. I've been trying to find a solution for this for the past few days, but found nothing useful.

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

```php
ThemeName_Kirki::add_field( 'themename_config', [
'type' => 'color',
'settings' => 'themename_site_header_border',
'label' => __( 'Site Header Bottom Border', 'themename' ),
'section' => 'themename_header_colors',
'default' => '',
'choices' => [ 'alpha' => true, ],
'output' => [
[ 'element' => '.site-header', 'property' => 'border-bottom', 'value_pattern' => '1px solid $' ],
],
'transport' => 'auto',
]);
```

**Comment by mapsteps** [comment]
Hi @idlevibes95, quick question. Why deactivate Kirki?

**Comment by JiveDig** [comment]
I'm seeing a similar issue with radio-buttonset in v4. May be worth a new issue but posting here since it's similar.

If I have a value in the default, it is always used in the output. If I make it empty or remove the default param altogether, it works.

```
new \Kirki\Field\Radio_Buttonset(
	[
		'settings'        => 'header-right-menu-alignment',
		'section'         => $section,
		'option_type'     => 'option',
		'option_name'     => mai_get_handle(),
		'label'           => __( 'Header Right Menu Alignment', 'mai-engine' ),
		'default'         => 'flex-end',
		'choices'         => [
			'flex-start' => __( 'Left', 'mai-engine' ),
			'center'     => __( 'Center', 'mai-engine' ),
			'flex-end'   => __( 'Right', 'mai-engine' ),
		],
		'output'          => [
			[
				'element'  => '.header-right',
				'property' => '--menu-justify-content',
			],
		],
	]
);
```
Making it `'default' => '',` or removing that line, it works. Otherwise it _always_ outputs `flex-end` no matter which choice is actually saved,

I've checked the db and it shows `flex-start` but `flex-end` is still rendered in the inline styles.

**Comment by JiveDig** [comment]
Okay my issue was related to not needing `option_name` but instead making `settings` value an array as mentioned here https://github.com/kirki-framework/kirki/issues/2443#issuecomment-1032877253. So this may be a separate issue.

**Comment by idlevibes95** [comment]
@MapSteps

It's mostly about people uploading the theme before activating Kirki and the theme being a mess at first, but I've done it a different way now so everything looks good with and without Kirki.

**Comment by mapsteps** [comment]
I'm closing this as the original issue here has to do with Kirki not being installed. @JiveDig, can you please open a separate issue for https://github.com/kirki-framework/kirki/issues/2446#issuecomment-1032795596

Thank you.
