### ISSUE TITLE
Docs say config is not needed, but CSS module uses it

### ISSUE THREAD

**Issue by JiveDig** [presscodes/kirki#2447]
Using 4.0.20 on a local test site.

We still need a workaround for some typography related things from https://github.com/kirki-framework/kirki/issues/2415 and https://github.com/kirki-framework/kirki/issues/2019.

I understand that the config is no longer needed for actual field controls/settings/output (via https://kirki.org/docs/setup/config/) but I couldn't get `kirki_{$config_id}_styles` filter to work and after digging in `Kirki\Module\CSS` module I realized those filters are still running, and looking for a config. This is a bit confusing now as I'm not sure what the config is doing. I'm happy to leave it, mostly looking for clarity, or an easier way to manipulate the rendered CSS to do the things mentioned in the above Issues.

Thanks :)

**Comment by contactjavas** [comment]
Hi @JiveDig , I'm not able yet to check #2415 and #2019 deeper.
But if the config is not defined, it will be `global` then. 
Could you try to add your filter to `kirki_global_styles` hook? Would that help?

**Comment by JiveDig** [comment]
Where is `kirki_global_styles`? I don't see that in the source. I couldn't find any filter that actually ran for CSS output without the config. Can you point me to the source?

**Comment by contactjavas** [comment]
I mean, if `$config_id` is not defined, then Kirki will assign the config_id as `global`.
So `kirki_{$config_id}_styles` in this case becomes `kirki_global_styles`.

Or, if you would like to manipulate the value directly, there is [`kirki_get_value`](https://github.com/kirki-framework/kirki/blob/79b3120274357404a7e052746de34ab9704ad7a0/packages/kirki-framework/module-css/src/CSS/Generator.php#L161) hook.

**Comment by JiveDig** [comment]
Ahh I didn't realize config_id is `global` if there isn't a config defined. This works, thanks.
