### ISSUE TITLE
Undefined index 'required' when using sanitize_callback as function

### ISSUE THREAD

**Issue by JiveDig** [presscodes/kirki#2448]
Kirki 4.0.20

![image](https://user-images.githubusercontent.com/540990/152881693-d01b95d1-7dfa-42f2-bf22-3ac8df75c561.png)

I have this:

```
'active_callback' => function() {
	return true;
},
```

and get the above error.

There's 2 issues that I see (only looking briefly):

1. Needs an `isset( $field['required'] )` here:
<img width="853" alt="image" src="https://user-images.githubusercontent.com/540990/152881985-10cb8510-f3a6-4059-83ab-490fa2491fdc.png">

2. There is only a check for `is_array( $field['active_callback'] )`. It needs to check if callable somewhere in there too, right?

**Comment by mapsteps** [comment]
Fixed. Will go live with the next update. Thanks for reporting! :) @JiveDig

**Comment by JiveDig** [comment]
I added the fix manually to test and all good here 👍. Thanks :)
