### ISSUE TITLE
error in version 4.0.20

### ISSUE THREAD

**Issue by mr-tempter** [presscodes/kirki#2451]
When upgrading to version 4.0.20
happening crash website

error report:

***/wordpress/wp-content/plugins/codeless-builder/include/core/kirki-setup/codeless_custom_section.php. Сообщение об ошибке: Uncaught Error: Class 'WP_Customize_Section' not found in ***/wordpress/wp-content/plugins/codeless-builder/include/core/kirki-setup/codeless_custom_section.php:3
Stack trace:
#0 ***/wordpress/wp-content/plugins/codeless-builder/include/core/cl-kirki-setup.php(93): require_once()
#1 ***/wordpress/wp-includes/class-wp-hook.php(307): Cl_Kirki_Setup->load_custom_section(Array)
#2 ***/wordpress/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#3 ***/wordpress/wp-content/plugins/kirki/packages/kirki-framework/compatibility/src/deprecated/filters.php(13): apply_filters('kirki/section_t...', Array)
#4 ***wordpress/wp-includes/class-wp-hook.php(307): Kirki\Compatibility\Deprecated->{closure}(Array)
#5 ***/wordpress/wp-includes/plugin.php(189): W

**Comment by mapsteps** [comment]
Seems like this will be sorted very soon! https://github.com/codelessteam/codeless-page-builder/issues/1

**Comment by mapsteps** [comment]
Codeless v1.1 has just released :) Please try and update Codeless page builder to the latest version. Ideally before updating Kirki to version 4. This should solve the issue.
