### ISSUE TITLE
[Dimension Field Throws Error

### ISSUE THREAD

**Issue by danfisher85** [presscodes/kirki#2454]
### Issue description:
I updated Kirki to v4.0.20 and got the following issues

Message `count(): Parameter must be an array or an object that implements Countable`
Location `wp-content/plugins/kirki/packages/kirki-framework/field-dimensions/src/Dimensions.php:105`

Message `Invalid argument supplied for foreach()`
Location `wp-content/plugins/kirki/packages/kirki-framework/field-dimensions/src/Dimensions.php:136`

![CleanShot 2022-02-09 at 02 10 48](https://user-images.githubusercontent.com/7786257/153102740-e252875a-542d-4d8d-b385-84e761cc8c7e.png)

### Version used:
4.0.20

### Using theme_mods or options?
theme_mod

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'escapium_config', array(
	'type'        => 'dimension',
	'settings'    => 'esc_page_heading_paddings_mobile',
	'label'       => esc_attr__( 'Page Heading Paddings - Mobile', 'escapium' ),
	'description' => esc_attr__( 'Set paddings for Mobile devices.', 'escapium' ),
	'section'     => 'esc_section_page_heading',
	'default'     => '60px',
	'output'      => array(
		array(
			'element'     => '.page-heading__inner',
			'property'    => 'padding-top',
			'media_query' => '@media (min-width: 576px)',
		),
		array(
			'element'     => '.page-heading__inner',
			'property'    => 'padding-bottom',
			'media_query' => '@media (min-width: 576px)',
		),
	),
) );
```

**Comment by mapsteps** [comment]
Hey @danfisher85,

does the error go away if you remove that particular field?

I'm asking because you're mentioning the `dimensions` field that throws the error but the code-snippet provided is a `dimension` (singular) field.

**Comment by danfisher85** [comment]
Hey @MapSteps ,
You're right! The dimensions fields are ok.
The issue is caused by the following code

```
Kirki::add_field( 'escapium_config', array(
	'type'        => 'spacing',
) );
```

Thanks for your assistance! It can be closed :)
