### ISSUE TITLE
Palettes doesn't work with latest version of Kirki

### ISSUE THREAD

**Issue by idlevibes95** [presscodes/kirki#2455]
### Issue description:
I'm using the latest version of Kirki and the palettes (the colors you add to choices) for the Color and Multicolor controls doesn't work. I looked at the documentation but it doesn't mention the palettes choice anywhere (I tried with palette, too). It used to work with the previous version of Kirki, but not since updating.

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

**Color control:**
```php
new \Kirki\Field\Color([
    'settings' => 'link_color',
    'label' => __( 'Link Color', 'pom' ),
    'section' => 'colors',
    'priority' => 4,
    'default' => '#b4ae97',
    'choices' => [
        'alpha' => true,
        'palettes' => [ '#000000', '#ffffff', '#b19d85', '#7b7459', '#ede8e2', '#d9cfc3', '#b4ae97', '#8f8767' ],
    ],
]);
```

**Multicolor control:**
```php
new \Kirki\Field\Multicolor([
    'settings' => 'blockquote_colors',
    'label' => esc_html__( 'Blockquote Color, Background and Border', 'pom' ),
    'section' => 'colors',
    'priority' => 2,
    'choices' => [
        'color' => esc_html__( 'Color', 'pom' ),
        'background' => esc_html__( 'Background', 'pom' ),
        'border' => esc_html__( 'Border', 'pom' ),
        'palettes' => [ '#000000', '#ffffff', '#b19d85', '#7b7459', '#ede8e2', '#d9cfc3', '#b4ae97', '#8f8767' ],
    ],
    'alpha' => true,
    'default' => [
        'color' => '',
        'background' => '',
        'border' => '',
    ],
]);
```

**Comment by contactjavas** [comment]
Hi @idlevibes95 , thanks for letting us know.
We will fix this soon and will update it here.

**Comment by contactjavas** [comment]
Hi @idlevibes95 , I'll bring back the `palettes` choice.
But for now, you can replace `palettes` keyword  with `swatches`. That should work.

**Comment by idlevibes95** [comment]
That's great, thank you!

**Comment by idlevibes95** [comment]
I actually just tried it for Multicolor, but it doesn't work there (not in choices or outside of choices).

**Comment by contactjavas** [comment]
Hi @idlevibes95 the `palettes` issue both on color control and in multicolor have been fixed.
The fix will be available in the next release.

Fyi, in color control, the `palettes` choice is inside `choices` argument while in multicolor, the `palettes` argument is **outside** of `choices` argument.

For now, let me close this issue.
Thanks! :)

**Comment by JiveDig** [comment]
> Fyi, in color control, the palettes choice is inside choices argument while in multicolor, the palettes argument is outside of choices argument.

@contactjavas That's an important note. Can the docs get updated to reflect the correct way(s) to use `palettes` param?

**Comment by JiveDig** [comment]
Just tested this and I can't get palettes to work at all with `new \Kirki\Field\Color(` no matter what I try, using `4.0.21`. The `kirki_default_color_swatches` works fine for me so I can have defaults everywhere except color picker in repeaters which still use the old iris color picker.

**Comment by contactjavas** [comment]
Hi @JiveDig , is it still using the same codes as in the example above?

**Comment by contactjavas** [comment]
Oh, you are not the thread starter :). Could you please provide / paste your code here @JiveDig ?
Thanks :)

**Comment by JiveDig** [comment]
Interesting, I don't know what my issue was prior but it works now for the Color field. It doesn't work when the old color field is used as a repeater field row. It'd be great to be able to use Color in a repeater and get the new react field.
