### ISSUE TITLE
Hola no funciona el plugin en mi wordpress mi pagina no carga bien los vehiculos www.tucarromaracaibo.com

### ISSUE THREAD

**Issue by castilloeric18** [presscodes/kirki#2456]
### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

**Comment by castilloeric18** [comment]
Desde la ultima actualizacion rompio mi sitio no funciona bien.

**Comment by mapsteps** [comment]
Hi @castilloeric18,

what theme are you using? Also, please notify the developer/s of the theme you're using about the incompatibility with the latest version of Kirki. This is something they might want to look into. Feel free to send them the link to this issue so they can join the discussion.

Thank you.

**Comment by castilloeric18** [comment]
Hello the theme I am using is called corify, I notified the creator of the
theme but apparently the plugin is since everything was working fine until
its last update. for example when I see the vehicle here it goes wrong.
https://tucarromaracaibo.com/listing/prueba-f/


*Ing. Eric Castillo*

*Director*

*Telf: +58 414-669.75.63*

*Maracaibo / Venezuela*

***@***.*** <http://goog_1922852946/>

**Comment by mapsteps** [comment]
To temporarily address this issue, you can manually downgrade to the previous version of Kirki. You can download version 3.1.9 here - https://downloads.wordpress.org/plugin/kirki.3.1.9.zip

We will have to have the developers of the theme have to chime in on this as we don't have access to the theme itself.
