### ISSUE TITLE
Risk of undefined error when misconfigured output

### ISSUE THREAD

**Issue by sebastianthulin** [presscodes/kirki#2457]
### Issue description:
Detected a "misconfiguration" in my output param's for some fields. Kirki happily took these misconfigurations and responded with loads of undefined errors. Some sort of warning may be suitable here. 

https://github.com/kirki-framework/module-postMessage/blob/master/src/Postmessage.php#L65 

```php
if ( empty( $args['js_vars'] ) && ! empty( $args['output'] ) && is_array( $args['output'] ) ) {
	foreach ( $args['output'] as $output ) {
		// Solves the problem, but may throw a warning instead.
		if ( ! is_array( $output ) ) {
			continue;
		}

		$output['element']  = isset( $output['element'] ) ? $output['element'] : ':root';
		$output['element']  = is_array( $output['element'] ) ? implode( ',', $output['element'] ) : $output['element'];
		$output['function'] = isset( $output['function'] ) ? $output['function'] : 'style';
		$js_vars[]          = $output;
	}
}
```

### Version used:
4.0.20

### Using theme_mods or options?
Theme mods. 

### Code to reproduce the issue (config + field(s))
```php
\Kirki::add_field(
	\Municipio\Customizer::KIRKI_CONFIG,
	[
		'type'     => 'select',
		'settings' => 'header_apperance',
		'label'    => esc_html__( 'Apperance', 'municipio' ),
		'section'  => self::SECTION_ID,
		'default'  => 'casual',
		'priority' => 10,
		'choices'  => [
			'casual'   => esc_html__( 'Casual (Small sites)', 'municipio' ),
			'business' => esc_html__( 'Business (large sites)', 'municipio' ),
		],
		'output'   => [
			'type' => 'controller',
		],
	]
);
```
          
 Would be nice to allow a official way to add my own output types (which is what i'm doing here), if you decide to throw a fatal error in the future.

**Comment by contactjavas** [comment]
Hi @sebastianthulin , when the CSS output is accessed in front-end, there should be a PHP warning/notice.
Please look at this line: [module-css/src/CSS.php#L122](https://github.com/kirki-framework/module-css/blob/8684b335be44382c52a61e7eda3bf0cfdfabbc2f/src/CSS.php#L122)

That's also maybe why there was a report in issue #2450 .

That line should be enough right?

**Comment by sebastianthulin** [comment]
You are correct. This is being throwed, but code further down the road is still running with insufficient error handling throwing native php warnings too.

**Comment by contactjavas** [comment]
Hi @sebastianthulin , thanks for your suggestion!

`__doing_it_wrong` has been implemented to handle miss-formatted `output` argument.
You can check [this commit](https://github.com/kirki-framework/module-postMessage/commit/e53eb3361bae51b6453e67f3f8690c61b1254707) if you would like.

This change will be shipped to the next release.
Let me close this issue :)
