### ISSUE TITLE
Choosing which google fonts-families to use does not work for custom selection.

### ISSUE THREAD

**Issue by ionburdianov** [presscodes/kirki#2459]
### Issue description:
In version 3 of the plugin, we used a selection of the Google fonts we needed.
But in version 4, our selection does not work, instead of the selected ones, all google fonts are displayed.
I checked it as indicated in the documentation and it does not work either,
https://kirki.org/docs/controls/typography/#google-fonts

### Version used:
4.0.20

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
new \Kirki\Field\Typography(
	[
		'settings'    => 'typography_setting',
		'label'       => esc_html__( 'Typography Control', 'kirki' ),
		'description' => esc_html__( 'The full set of options.', 'kirki' ),
		'section'     => 'fonts_colors',
		'priority'    => 10,
		'transport'   => 'auto',
		'default'     => [
			'font-family'     => 'Roboto',
			'variant'         => 'regular',
			'font-style'      => 'normal',
			'color'           => '#333333',
			'font-size'       => '14px',
			'line-height'     => '1.5',
			'letter-spacing'  => '0',
			'text-transform'  => 'none',
			'text-decoration' => 'none',
			'text-align'      => 'left',
		],
		'output'      => [
			[
				'element' => 'body',
			],
		],
		'choices' => [
			'fonts' => [
				'google' => [ 'Roboto', 'Open Sans', 'Lato', 'Noto Serif', 'Noto Sans' ],
			],
		],
	]
);
```

![image](https://user-images.githubusercontent.com/28696444/153425691-a2cd0d3f-8e9a-42bb-b437-4120c58daf52.png)

**Comment by mapsteps** [comment]
Confirmed. Thanks for reporting!

**Comment by contactjavas** [comment]
Hi @BootWP , this issue has been fixed and the fix will be available in the next release.
For now, let me close this issue :)

Thanks for reporting

**Comment by ionburdianov** [comment]
Thank you very much, I checked and everything works as it should.
