### ISSUE TITLE
Footer logo missing

### ISSUE THREAD

**Issue by tmsmasum** [presscodes/kirki#2464]
### Version used:
4.0.21

### Using `theme_mods` or `options`?
`theme_mods`

### PHP error messages that might be related
```bash

```

### JS error messages that might be related
```bash

```

### Code to reproduce the issue (config + field(s))
```php

```

**Comment by mapsteps** [comment]
Hi @tmsmasum,

can you please provide additional information on this?
How would we replicate the issue?
What's indicating that this is caused by Kirki?
What theme are you using?
Have you notified the original theme developer about this issue?

**Comment by tmsmasum** [comment]
I'm using [Seocify – SEO And Digital Marketing Agency WordPress Theme](https://plugintheme.net/shop/seocify-seo-and-digital-marketing-agency-wordpress-theme/)
