### ISSUE TITLE
Output not working when saving as option

### ISSUE THREAD

**Issue by JiveDig** [presscodes/kirki#2465]
### Issue description:
I've reduced it down to simple examples where it works as theme_mod but not as option. So far I've confirmed this with Radio and Button_Set fields but it possibly happens with others as well.

To clarify, there **IS** output, but it always uses the default, not the saved value.

### Version used:
4.0.21

### Using `theme_mods` or `options`?
`options`

### Code to reproduce the issue (config + field(s))
**Broken**
Swap out `new \Kirki\Field\Radio(` for `new \Kirki\Field\Radio_Buttonset(` to test with different fields.
```
new \Kirki\Field\Radio(
	[
		'settings'    => 'kirki_demo_radio_buttonset',
		'option_type' => 'option',
		'option_name' => 'mai-engine-test',
		'label'       => esc_html__( 'Radio-Buttonset Control', 'kirki' ),
		'description' => esc_html__( 'Sample of radio-buttonset control.', 'kirki' ),
		'section'     => 'mai-engine-menus', // Change this to a section you have.
		'default'     => 'black',
		'choices'     => [
			'black' => esc_html__( 'Black', 'kirki' ),
			'blue'  => esc_html__( 'Blue', 'kirki' ),
			'red'   => esc_html__( 'Red', 'kirki' ),
		],
		'output'          => [
			[
				'element'  => 'body',
				'property' => 'background',
			],
		],
	]
);
```

**Working** 
Same code as above but without `option_type` and `option_name` values.
```
new \Kirki\Field\Radio(
	[
		'settings'    => 'kirki_demo_radio_buttonset',
		'label'       => esc_html__( 'Radio-Buttonset Control', 'kirki' ),
		'description' => esc_html__( 'Sample of radio-buttonset control.', 'kirki' ),
		'section'     => 'mai-engine-menus', // Change this to a section you have.
		'default'     => 'black',
		'choices'     => [
			'black' => esc_html__( 'Black', 'kirki' ),
			'blue'  => esc_html__( 'Blue', 'kirki' ),
			'red'   => esc_html__( 'Red', 'kirki' ),
		],
		'output'          => [
			[
				'element'  => 'body',
				'property' => 'background',
			],
		],
	]
);
```

**Comment by JiveDig** [comment]
Trying to debug this a bit. The `Output` class doesn't get a value when it's `option` but it does when it's `theme_mod`. I'm dumping data right in `__construct` like this:

```
	public function __construct( $config_id, $output, $value, $field ) {
		$this->value  = $value;
		$this->output = $output;
		$this->field  = $field;

		ray( $value );

		$this->parse_output();
	}
```

**Comment by mapsteps** [comment]
Hey @JiveDig, thank you for narrowing it down! We were able to replicate this and are going to issue a fix asap. This is basically the same issue as described here - https://github.com/kirki-framework/kirki/issues/2466

We are on it :)

**Comment by JiveDig** [comment]
Ah I missed that issue, my bad. I'll keep up over there. TY.
