### ISSUE TITLE
Kirki generates styles in Gutenberg editor

### ISSUE THREAD

**Issue by danfisher85** [presscodes/kirki#2467]
### Issue description:
I'm using the Typography field to style H1 heading with default settings in my theme. The default heading color is white (`#ffffff`) because the theme is dark. However, for some reason, Kirki generates CSS that populates to Gutenberg editor. Because of this, the white color applies to H1 in Gutenberg editor and the page heading color is white on white (see screenshot https://cln.sh/tI0xaN)
This CSS is generated in `.../wp-content/plugins/kirki/packages/kirki-framework/module-css/src/CSS/Output.php` see screenshot https://cln.sh/Tdswzg

### Version used:
4.0.22

### Using `theme_mods` or `options`?
`theme_mods`

### Code to reproduce the issue (config + field(s))
```php
new \Kirki\Field\Typography( [
	'settings'    => 'esc_typography_h1',
	'label'       => esc_attr__( 'H1 Heading', 'escapium' ),
	'section'     => 'esc_section_typography_headings',
	'choices'     => array(
		'fonts' => array(
			'google' => array(
				'popularity',
				apply_filters( 'escapium_google_fonts_number', 50 )
			),
		),
	),
	'default'     => array(
		'font-family'    => 'Montserrat',
		'variant'        => '700',
		'font-size'      => '2.75rem',
		'line-height'    => '1.2',
		'letter-spacing' => '0',
		'color'          => '#fff',
		'text-transform' => 'none',
	),
	'output'      => array(
		array(
			'element' => 'h1, .h1',
		),
	),
] );
```

**Comment by mapsteps** [comment]
Hi @danfisher85,

quick question. Are you trying to disable Gutenberg support in Kirki altogether (meaning no styles will apply to the Gutenberg editor) or on a per-control basis?

Thanks.

**Comment by danfisher85** [comment]
Hi @MapSteps,
I'm trying to disable all Kirki styles in Gutenberg editor. Is it possible?
In my case I don't add theme styles to the Gutenber, I just basic ones.
BR

**Comment by DeoThemes** [comment]
There was a setting **context** prior to version 4. I wonder is this option is still working, since I tried to output styles only in the editor and it didn't work:

```
array(
	'element' => '.edit-post-visual-editor .editor-styles-wrapper',
	'context' => array( 'editor' ),
)
```

**Comment by mapsteps** [comment]
Hi @danfisher85,

with the next release, you can define a constant (example below) to disable the CSS output in Gutenberg.
Outputting Kirki styles in Gutenberg is the default behaviour since V4 so opting in for it is no longer necessary. 

Disable Gutenberg styles globally:
`define( 'KIRKI_NO_GUTENBERG_OUTPUT', true );`

**Comment by danfisher85** [comment]
@MapSteps thanks a lot! :)
