### ISSUE TITLE
Customize Missing options on new version. 

### ISSUE THREAD

**Issue by fudojahic** [presscodes/kirki#2472]
### Issue description:
Customize Missing options on new version. 

### Version used:
4.0.21

### Using `theme_mods` or `options`?
`theme_mods`

### PHP error messages that might be related
```bash

```

### JS error messages that might be related
```bash

```

### Code to reproduce the issue (config + field(s))
```php

```
How can I downgrade this. It broke everything

**Comment by contactjavas** [comment]
Hey @fudojahic, can you pelase update to the latest version (`v4.0.22`)?

**Comment by fudojahic** [comment]
> Hey @fudojahic, can you pelase update to the latest version (`v4.0.22`)?

I do and that v4.0.22 is breaking the customize. So i had to downgrade to 3.1.9 and then everything gets back to normal.

**Comment by mapsteps** [comment]
Okay, let's dive a bit deeper here. Can you please enable debugging as described in this article (https://wp-pagebuilderframework.com/docs/debugging/) and try to update to 4.0.22 again? The contents of the debug.log file should give us more insights on what's causing the issue.

Thank you for testing!

**Comment by fudojahic** [comment]
> Okay, let's dive a bit deeper here. Can you please enable debugging as described in this article (https://wp-pagebuilderframework.com/docs/debugging/) and try to update to 4.0.22 again? The contents of the debug.log file should give us more insights on what's causing the issue.
> 
> Thank you for testing!

 think for now i will stick with 3.1.9 as my clients really need the website.

**Comment by mapsteps** [comment]
Okay, that's totally up to you. If you want us to look into this further at any point in the future, please let us know.

**Comment by fudojahic** [comment]
> Okay, that's totally up to you. If you want us to look into this further at any point in the future, please let us know.

Will do! i
