### ISSUE TITLE
A PHP session was created by calling the session_start() function. This interferes with REST API and loopback requests. The session must be closed by session_write_close() before making any HTTP requests.

### ISSUE THREAD

**Issue by Danielw10** [presscodes/kirki#2474]
In wordpress diagnostics, the following problem is presented in the kirki customizer framework, when I disable kirki it disappears.

It has to do with updating to the latest versions of PHP
7.0 to 7.4

A PHP session was created by calling the session_start() function. This interferes with REST API and loopback requests. The session must be closed by session_write_close() before making any HTTP requests.

The REST API is a way for WordPress, and other applications, to communicate with the server. An example is the block editor canvas, which relies on the API to display and save your posts and pages.

The REST API request failed due to the following error.
Error: cURL error 28: Operation timed out after 10003 milliseconds with 0 bytes received (http_request_failed)

PHP Compatibility Checker plugin diagnosed the following conflicts

FILE: /home1/danielw10/public_html/wp-content/plugins/kirki/packages/kirki-framework/util/src/Helper.php

FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE

48 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$array" was used, and possibly changed (by reference), on line 36.

**Comment by Danielw10** [comment]
Plugin code needs to be reworked to adapt to new guidelines of new PHP versions

**Comment by mapsteps** [comment]
Hi @Danielw10,

We do not call `session_start()`. What version of Kirki do you have installed? Also, is it from the WordPress repository or here on GitHub?

Thank you.

**Comment by mapsteps** [comment]
I'm closing this as it seems to be a duplicate (https://github.com/kirki-framework/kirki/issues/2471). Let's continue there! :)
