### ISSUE TITLE
Undefined index 'transport'

### ISSUE THREAD

**Issue by mircobabini** [presscodes/kirki#2476]
### Issue description:
My site is cluttered of notices because of this line https://github.com/kirki-framework/kirki/blob/da3b1976e39b61c8e7e5210a3d01adbdacad0926/packages/kirki-framework/compatibility/src/Kirki.php#L274

I'm not a direct consumer. I'm using [Cera Intranet Community Theme](https://themeforest.net/item/cera-intranet-community-theme/24872621) and probably they don't se that transport arg.

What if we change that check like

`if ( isset( $args['transport'] ) && 'postMessage' === $args['transport'] ) {`

### Version used:
4.0.21

**Comment by mapsteps** [comment]
This is going to be fixed with the upcoming release. Thank you for reporting.
