### ISSUE TITLE
Google fonts are preconnected in header even when loaded locally

### ISSUE THREAD

**Issue by JiveDig** [presscodes/kirki#2478]
In kirki-framework/kirki/packages/kirki-framework/module-webfonts/src/Webfonts/Embed.php and kirki-framework/kirki/packages/kirki-framework/module-webfonts/src/Webfonts/Async.php the `resource_hints()` method is preconnecting to Google even though the fonts are loading locally. This should not be happening IMO.

Preconnecting makes sense when the fonts are actually loaded via Google as a fallback for the times the files aren't available locally for whatever reason. It seems `resource_hints()` should have a guard clause to see if the fonts are available locally first.

### Version used:
4.0.23

### Using `theme_mods` or `options`?
Either.

![CleanShot 2022-04-22 at 09 29 22](https://user-images.githubusercontent.com/540990/164724284-bb62d5ad-7a6c-4721-bef7-620dab804e67.jpeg)

**Comment by deckerweb** [comment]
Hi,
we have this issue on all our sites that are using Mai Themes which uses Kirki. We only use the fonts locally as provided by Mai but everywhere the fonts.gstatic.com gets injected. This is an issue for privacy reasons in the EU and gets mentioned by all the (good) Cookie Info plugins that feature a scanner.

I tried to come up with a filter / action to remove the injection but it did not work... 

We would suggest a solution as @JiveDig mentioned above: when using fonts locally don't inject this line, I guess that would be the most convienent for all involved.

**Comment by ali-han** [comment]
i have the same problem

**Comment by mapsteps** [comment]
This will be fixed with the upcoming release, thanks for reporting!
