### ISSUE TITLE
Multicolor customizer output

### ISSUE THREAD

**Issue by x-bull** [presscodes/kirki#2480]
### Issue description:
Multicolor field CSS output in customizer is incorrect (on live site is correct). 
It add "choices" as suffix to output property:
Example for "font" choice:
Instead color: xxxx;
the output in customizer is color-font:xxx;

It was ok in 3.1.9, this issue is since v4+

![multicolor](https://user-images.githubusercontent.com/14072537/166202524-2e1411d2-e48c-43e7-a2dd-0dd1ca74d8e1.jpg)

### Version used:
4.0.23

### Using `theme_mods` or `options`?
`theme_mods`

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field('test', array(
    'type' => 'multicolor',
    'settings' => 'mainmenu_desc_color',
    'label' => esc_attr__('Menu badge', 'test'),
    'section' => 'main_menu',
    'default' => '',
    'transport' => 'auto',
    'priority' => 40,
    'choices' => array(
        'font' => esc_attr__('Font', 'test'),
        'bg' => esc_attr__('Background', 'test'),
    ),
    'default' => array(
        'font' => '',
        'bg' => '',
    ),
    'output' => array(
        array(
            'choice' => 'font',
            'element' => '.menu-item .menu-description',
            'property' => 'color',
        ),
        array(
            'choice' => 'bg',
            'element' => '.menu-item .menu-description',
            'property' => 'background-color',
        ),
      
    ),
));

```

**Comment by mapsteps** [comment]
This is going to be fixed with the upcoming release. Thank you for reporting.
