### ISSUE TITLE
WP repo and github are 4.1.1 but the github Releases (and packagist) are still at 4.1.0

### ISSUE THREAD

**Issue by JiveDig** [presscodes/kirki#2504]
I'm thinking a Release here on github was just missed? Wondering if some of the missing Google Fonts were added in 4.1.1 as well :)

**Comment by markbosky** [comment]
+1 I was wondering this as well

**Comment by JiveDig** [comment]
Closed via https://github.com/themeum/kirki/releases/tag/v4.2.0 which auto-updated here https://packagist.org/packages/kirki-framework/kirki

TY!
